server.port=8083
spring.application.name=transaction-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/financedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka Producer Config
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SSL}
spring.kafka.properties.ssl.truststore.type=${KAFKA_SSL_TRUSTSTORE_TYPE:}
spring.kafka.properties.ssl.truststore.certificates=${KAFKA_SSL_TRUSTSTORE_CERTS:}
spring.kafka.properties.ssl.keystore.type=PEM
spring.kafka.properties.ssl.keystore.certificate.chain=${KAFKA_SSL_CLIENT_CERT:}
spring.kafka.properties.ssl.keystore.key=${KAFKA_SSL_CLIENT_KEY:}
# Custom application config for other service URLs
app.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:8082/api/accounts}
